export const INTERFACE_TYPE = {
    BookRepository: Symbol.for("BookRepository"),
    BookInteractor: Symbol.for("BookInteractor"),
    BookController: Symbol.for("BookController"),
    Mailer: Symbol.for("Mailer"),
    MessageBroker: Symbol.for("MessageBroker"),
    AccountController:Symbol.for("AccountController"),
    AccountInteractor:Symbol.for("AccountInteractor"),
    UserRepository:Symbol.for("UserRepository"),
    JwtTokenService:Symbol.for("JwtTokenService"),
    RefreshTokenRepository:Symbol.for("RefreshTokenRepository"),
    uuidService:Symbol.for("uuidService"),
    UserInteractor: Symbol.for("UserInteractor"),
    UserController:Symbol.for("UserController"),
  };